name: Publish NuGet

on: 
  #pull_request:
  #  branches: 
  #  - master
  ['deployment']

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Restore
      run: dotnet restore BitlyDotNet

    - name: Build
      run: dotnet build BitlyDotNet --configuration Release --no-restore
    
    - name: Pack
      run: dotnet pack BitlyDotNet --configuration Release -o finalpackage --no-build --version-suffix action-testing

    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: nupkg
        path: finalpackage

  deploy:
      name: Deploy Packages
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Download Package artifact
          uses: actions/download-artifact@master
          with:
            name: nupkg
            
        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.2
          with:
            nuget-version: latest

        - name: Setup .NET SDK tools
          uses: actions/setup-dotnet@master
          with:
            dotnet-version: '3.1.100'
            source-url: https://www.nuget.org/api/v2/package
          env:
            NUGET_AUTH_TOKEN: ${{ secrets.NUGET_ORG_TOKEN }} 

        - name: Push to NuGet.org (using dotnet)
          env:
            NUGET_AUTH_TOKEN: ${{ secrets.NUGET_ORG_TOKEN }} 
          run: dotnet nuget push nupkg/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate
